### ISSUE TITLE
Exception on Windows

### ISSUE THREAD

**Issue by dimitvassilev** [DivineOmega/DO-File-Cache#4]
Hi,
I am on Windows and therefore the sys_getloadavg() function does not exist and even though I haven't touched the default configuration  "'unixLoadUpperThreshold' => -1," as the suggestion in the exception message reads, the exception is nevertheless thrown. I think this check
https://github.com/DivineOmega/DO-File-Cache/blob/261c6e30a0de8cd325f826d08b2e51b2e367a1a3/src/DOFileCache.php#L122

should be done instead before this line https://github.com/DivineOmega/DO-File-Cache/blob/261c6e30a0de8cd325f826d08b2e51b2e367a1a3/src/DOFileCache.php#L129.

Best regards,
Dimitar

**Comment by DivineOmega** [comment]
@dimitvassilev Thanks for bringing this to my attention!

This should be fixed in v2.0.3. Would you mind giving it a test and getting back to me?

**Comment by dimitvassilev** [comment]
Hi,
It's all good now, thanks a lot!

**Comment by DivineOmega** [comment]
@dimitvassilev My pleasure. Glad it helped. :+1:
