### ISSUE TITLE
Error suppression

### ISSUE THREAD

**Issue by marcovo** [DivineOmega/DO-File-Cache#5]
In the line, error suppression (`@`) is used:
https://github.com/DivineOmega/DO-File-Cache/blob/master/src/DOFileCache.php#L136

Unfortunately, upon heave use of this code, your error log will get cluttered with error messages. Surely the @ prevents errors to be written to standard output (/web browser), but errors are still written to custom error handlers and log files.

Hence, I propose to not use error suppression, and solve the real problem at hand here. Data is only serialized whenever it is not a string:
https://github.com/DivineOmega/DO-File-Cache/blob/master/src/DOFileCache.php#L52 , so to clarify: ints, bools and floats are serialized as well. My suggestion is to always serialize, strings too, and also always unserialize. This way the get procedure will not result in loads of notices in the log any more.

The only downside is that strings will have to be serialized, increasing some storage space and computation time. This does not outweight the benefit of having well-defined storage characteristics, imho.

Btw, I'm posting this as a user of the divineomega/password_exposed library, which is an example of this issue in practice.

**Comment by DivineOmega** [comment]
Thanks for this. I agree with all points here.

Feel free to open a PR if you wish. If not, I'll likely look into changing this within the next few days.

**Comment by DivineOmega** [comment]
This is now fixed in v2.0.4.

**Comment by marcovo** [comment]
Thanks a lot :) .

**Comment by DivineOmega** [comment]
My pleasure. 👍
